version: 2

sources:
  - name: staging
    description: > 
      This is the BigQuery instance containing the weather details
    database: data-eng-practice007
    schema: weather_details
    tables:
      - name: all_city_aqi
        description: >
          This table contains the AQI levels for all the recorded cities along with the level of each pollutant

models:
  - name: all_city_aqi_with_desc
    columns:
      - name: dt
        tests:
          - not_null
      
      - name: aqi
        tests:
          - accepted_values:
              values: [1,2,3,4,5]
              quote: false
      
      - name: aqi_level_description
        tests:
          - not_null
          - accepted_values:
              values: ['Good', 'Fair', 'Moderate', 'Poor', 'Very Poor']
      
      - name: city_name
        tests:
          - relationships:
              to: ref('country_coordinates_population')
              field: capital_city
            
seeds:
  - name: country_coordinates_population
    description: >
      "country_coordinates_population" is a table which contains the geo coordinates of different countries. This table is seeded by dbt before the actual models are generated.  